# Generated by Django 5.2.4 on 2025-08-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('emial', models.EmailField(max_length=150, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
