# Generated by Django 5.2.4 on 2025-08-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_django', '0002_rename_emial_samplemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
