# Generated by Django 5.2.4 on 2025-08-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_django', '0005_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
