# Generated by Django 5.2.4 on 2025-08-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_django', '0006_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=123)),
            ],
        ),
    ]
