# Generated by Django 5.2.4 on 2025-08-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_django', '0014_order_shipping_latitude_order_shipping_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_contact',
            field=models.CharField(blank=True, default='0000000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('cash_on_delivery', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
