# Generated by Django 5.2.4 on 2025-08-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_django', '0016_alter_order_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_contact',
            field=models.IntegerField(blank=True, default='0000000000', null=True),
        ),
    ]
