# Generated by Django 5.2.4 on 2025-08-22 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_django', '0017_alter_order_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Address can only contain letters, numbers, spaces, and , . - / # @ & ( )', regex='^[A-Za-z0-9\\s,.\\-/#@&()]+$')]),
        ),
    ]
