# Generated by Django 5.2.4 on 2025-08-22 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_django', '0018_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Shipping address must contain at least one special character: , . - / # @ & ( )', regex='^(?=.*[,.\\-/#@&()])[A-Za-z0-9\\s,.\\-/#@&()]+$')]),
        ),
    ]
